In [36]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import optuna
import joblib
from pathlib import Path

from optuna.samplers import TPESampler

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    roc_auc_score,
    f1_score,
    accuracy_score,
    classification_report,
    confusion_matrix
)

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

In [37]:
BASE_DIR = Path.cwd()
TRAIN_PATH = BASE_DIR / "train_loan_final.csv"
TEST_PATH = BASE_DIR / "test_loan_final.csv"

df_train = pd.read_csv(TRAIN_PATH)
df_test = pd.read_csv(TEST_PATH)

In [38]:
df_train.head()
df_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 32670 entries, 0 to 32669
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cust_id           32670 non-null  int64
 1   income_yearly     31038 non-null  float64
 2   debt_ratio        32670 non-null  str
 3   credit_rating     31038 non-null  float64
 4   amount_requested  32670 non-null  float64
 5   interest_pct      32670 non-null  float64
 6   gender_type       32670 non-null  str
 7   family_status     32670 non-null  str
 8   edu_bg            31038 non-null  str
 9   job_status        31038 non-null  str
 10  loan_reason       32670 non-null  str
 11  internal_grade    32670 non-null  str
 12  is_repaid         32670 non-null  float64
dtypes: float64(5), int64(1), str(7)
memory usage: 3.2 MB

In [39]:
df_train = df_train.drop(columns=["cust_id"])
cat_cols = ["gender_type", "family_status", "edu_bg", "job_status", "loan_reason", "internal_grade"]

for df in [df_train, df_test]:
    df["debt_ratio"] = pd.to_numeric(df["debt_ratio"], errors="coerce")

    for col in cat_cols:
        df[col] = df[col].astype(object).str.strip()

    df["gender_type"] = df["gender_type"].replace({"mAle": "Male"})
    df["job_status"] = df["job_status"].replace({"Employed_": "Employed"})

y = df_train["is_repaid"]
X = df_train.drop(columns=["is_repaid"])

X_test = df_test.drop(columns=["cust_id"])

df_train.info()
df_train.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 32670 entries, 0 to 32669
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   income_yearly     31038 non-null  float64
 1   debt_ratio        32025 non-null  float64
 2   credit_rating     31038 non-null  float64
 3   amount_requested  32670 non-null  float64
 4   interest_pct      32670 non-null  float64
 5   gender_type       32670 non-null  object
 6   family_status     32670 non-null  object
 7   edu_bg            31038 non-null  object
 8   job_status        31038 non-null  object
 9   loan_reason       32670 non-null  object
 10  internal_grade    32670 non-null  object
 11  is_repaid         32670 non-null  float64
dtypes: float64(6), object(6)
memory usage: 3.0+ MB

income_yearly       1632
debt_ratio           645
credit_rating       1632
amount_requested       0
interest_pct           0
gender_type            0
family_status          0
edu_bg              1632
job_status          1632
loan_reason            0
internal_grade         0
is_repaid              0
dtype: int64

In [ ]:
#config
RANDOM_STATE = 42

In [ ]:
NUMERIC_COLUMNS = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
CATEGORICAL_COLUMNS = X.select_dtypes(include=['object', 'string']).columns.tolist()

numeric_transformer = SimpleImputer(strategy='median')

categorical_transformer = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy="constant", fill_value="Missing")),
        ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
    ]
)

preprocessing = ColumnTransformer(
    transformers=[
        ('numeric', numeric_transformer, NUMERIC_COLUMNS),
        ('cat', categorical_transformer, CATEGORICAL_COLUMNS)
    ],
    remainder="drop"
)

In [7]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y)

skf = StratifiedKFold(
    n_splits = 5,
    shuffle = True,
    random_state=RANDOM_STATE
)

In [ ]:
def objective(trial):
    # XGBoost hyperparameters
    xgb_model = XGBClassifier(
        n_estimators=trial.suggest_int("xgb_n_estimators", 100, 800),
        max_depth=trial.suggest_int("xgb_max_depth", 2, 10),
        learning_rate=trial.suggest_float("xgb_learning_rate", 0.01, 0.3, log=True),
        subsample=trial.suggest_float("xgb_subsample", 0.6, 1.0),
        colsample_bytree=trial.suggest_float("xgb_colsample_bytree", 0.6, 1.0),
        min_child_weight=trial.suggest_int("xgb_min_child_weight", 1, 10),
        reg_alpha=trial.suggest_float("xgb_reg_alpha", 1e-8, 10.0, log=True),
        reg_lambda=trial.suggest_float("xgb_reg_lambda", 1e-8, 10.0, log=True),
        objective="binary:logistic",
        eval_metric="logloss",
        random_state=RANDOM_STATE,
        n_jobs=-1
    )


    # LightGBM hyperparameters
    lgbm_model = LGBMClassifier(
        n_estimators=trial.suggest_int("lgbm_n_estimators", 100, 600),
        max_depth=trial.suggest_int("lgbm_max_depth", 2, 12),
        learning_rate=trial.suggest_float("lgbm_learning_rate", 0.01, 0.3, log=True),
        num_leaves=trial.suggest_int("lgbm_num_leaves", 15, 127),
        subsample=trial.suggest_float("lgbm_subsample", 0.6, 1.0),
        colsample_bytree=trial.suggest_float("lgbm_colsample_bytree", 0.6, 1.0),
        reg_alpha=trial.suggest_float("lgbm_reg_alpha", 1e-8, 10.0, log=True),
        reg_lambda=trial.suggest_float("lgbm_reg_lambda", 1e-8, 10.0, log=True),
        random_state=RANDOM_STATE,
        n_jobs=-1,
        verbose=-1
    )

    # CatBoost hyperparameters
    cat_model = CatBoostClassifier(
        iterations=trial.suggest_int("cat_iterations", 100, 600),
        depth=trial.suggest_int("cat_depth", 2, 10),
        learning_rate=trial.suggest_float("cat_learning_rate", 0.01, 0.3, log=True),
        l2_leaf_reg=trial.suggest_float("cat_l2_leaf_reg", 1e-3, 10.0, log=True),
        random_seed=RANDOM_STATE,
        verbose=0,
        loss_function="Logloss"
    )

    # Meta model
    meta_model = LogisticRegression(
        C=trial.suggest_float("meta_C", 1e-4, 100.0, log=True),
        max_iter=3000,
        class_weight="balanced",
        random_state=RANDOM_STATE
    )

    # Stacking model
    stack_model = StackingClassifier(
        estimators=[
            ("xgb", xgb_model),
            ("lgbm", lgbm_model),
            ("cat", cat_model)
        ],
        final_estimator=meta_model,
        cv=skf,
        stack_method="predict_proba",
        n_jobs=-1,
        passthrough=False
    )

    # Full pipeline:
    # preprocessing -> stacking
    full_pipeline = Pipeline(
        steps=[
            ("preprocessor", preprocessing),
            ("model", stack_model)
        ]
    )

    scores = cross_val_score(
        full_pipeline,
        X_train,
        y_train,
        cv=skf,
        scoring="f1_macro",
        n_jobs=-1
    )

    return scores.mean()

In [9]:
study = optuna.create_study(
    direction="maximize",
    sampler=TPESampler(seed=42)
)

study.optimize(
    objective,
    n_trials=50,
    show_progress_bar=True
)

print("Best F1-Macro:", study.best_value)
print("Best parameters:")
print(study.best_params)

[I 2026-05-14 12:04:05,582] A new study created in memory with name: no-name-9dc1e72f-446f-4cd7-be6a-06ea3dfd95fd
Best trial: 0. Best value: 0.82003:   2%|▏         | 1/50 [01:10<57:14, 70.10s/it]

[I 2026-05-14 12:05:15,683] Trial 0 finished with value: 0.8200300834561368 and parameters: {'xgb_n_estimators': 362, 'xgb_max_depth': 10, 'xgb_learning_rate': 0.1205712628744377, 'xgb_subsample': 0.8394633936788146, 'xgb_colsample_bytree': 0.6624074561769746, 'xgb_min_child_weight': 2, 'xgb_reg_alpha': 3.3323645788192616e-08, 'xgb_reg_lambda': 0.6245760287469893, 'lgbm_n_estimators': 401, 'lgbm_max_depth': 9, 'lgbm_learning_rate': 0.010725209743171996, 'lgbm_num_leaves': 124, 'lgbm_subsample': 0.9329770563201687, 'lgbm_colsample_bytree': 0.6849356442713105, 'lgbm_reg_alpha': 4.329370014459266e-07, 'lgbm_reg_lambda': 4.4734294104626844e-07, 'cat_iterations': 252, 'cat_depth': 6, 'cat_learning_rate': 0.04345454109729477, 'cat_l2_leaf_reg': 0.014618962793704957, 'meta_C': 0.4689400963537689}. Best is trial 0 with value: 0.8200300834561368.

Best trial: 0. Best value: 0.82003:   4%|▍         | 2/50 [01:46<40:18, 50.38s/it]

[I 2026-05-14 12:05:52,261] Trial 1 finished with value: 0.8108283836546679 and parameters: {'xgb_n_estimators': 197, 'xgb_max_depth': 4, 'xgb_learning_rate': 0.03476649150592621, 'xgb_subsample': 0.7824279936868144, 'xgb_colsample_bytree': 0.9140703845572055, 'xgb_min_child_weight': 2, 'xgb_reg_alpha': 0.00042472707398058225, 'xgb_reg_lambda': 0.0021465011216654484, 'lgbm_n_estimators': 123, 'lgbm_max_depth': 8, 'lgbm_learning_rate': 0.0178601378893971, 'lgbm_num_leaves': 22, 'lgbm_subsample': 0.9795542149013333, 'lgbm_colsample_bytree': 0.9862528132298237, 'lgbm_reg_alpha': 0.18861495878553936, 'lgbm_reg_lambda': 5.514725787121931e-06, 'cat_iterations': 148, 'cat_depth': 8, 'cat_learning_rate': 0.044684675025045834, 'cat_l2_leaf_reg': 0.003077180271250686, 'meta_C': 0.09355380606452186}. Best is trial 0 with value: 0.8200300834561368.

Best trial: 2. Best value: 0.821305:   6%|▌         | 3/50 [03:24<56:18, 71.88s/it]

[I 2026-05-14 12:07:29,725] Trial 2 finished with value: 0.8213045586439083 and parameters: {'xgb_n_estimators': 124, 'xgb_max_depth': 10, 'xgb_learning_rate': 0.024112898115291985, 'xgb_subsample': 0.8650089137415928, 'xgb_colsample_bytree': 0.7246844304357644, 'xgb_min_child_weight': 6, 'xgb_reg_alpha': 0.0008325158565947976, 'xgb_reg_lambda': 4.609885087947832e-07, 'lgbm_n_estimators': 585, 'lgbm_max_depth': 10, 'lgbm_learning_rate': 0.24420460844911424, 'lgbm_num_leaves': 116, 'lgbm_subsample': 0.8391599915244341, 'lgbm_colsample_bytree': 0.9687496940092467, 'lgbm_reg_alpha': 6.257956190096665e-08, 'lgbm_reg_lambda': 5.805581976088804e-07, 'cat_iterations': 122, 'cat_depth': 4, 'cat_learning_rate': 0.03750796359625606, 'cat_l2_leaf_reg': 0.01217295809836997, 'meta_C': 9.38480071590954}. Best is trial 2 with value: 0.8213045586439083.

Best trial: 3. Best value: 0.823396:   8%|▊         | 4/50 [04:18<49:47, 64.96s/it]

[I 2026-05-14 12:08:24,066] Trial 3 finished with value: 0.8233955388709706 and parameters: {'xgb_n_estimators': 350, 'xgb_max_depth': 4, 'xgb_learning_rate': 0.06333268775321843, 'xgb_subsample': 0.6563696899899051, 'xgb_colsample_bytree': 0.9208787923016158, 'xgb_min_child_weight': 1, 'xgb_reg_alpha': 7.620481786158549, 'xgb_reg_lambda': 0.08916674715636537, 'lgbm_n_estimators': 199, 'lgbm_max_depth': 2, 'lgbm_learning_rate': 0.1601531217136121, 'lgbm_num_leaves': 94, 'lgbm_subsample': 0.8916028672163949, 'lgbm_colsample_bytree': 0.9085081386743783, 'lgbm_reg_alpha': 4.638759594322625e-08, 'lgbm_reg_lambda': 1.683416412018213e-05, 'cat_iterations': 158, 'cat_depth': 9, 'cat_learning_rate': 0.08330803890301997, 'cat_l2_leaf_reg': 0.021066486017042207, 'meta_C': 0.0002406301832072095}. Best is trial 3 with value: 0.8233955388709706.

Best trial: 3. Best value: 0.823396:  10%|█         | 5/50 [05:07<44:24, 59.21s/it]

[I 2026-05-14 12:09:13,074] Trial 4 finished with value: 0.8211616419799508 and parameters: {'xgb_n_estimators': 317, 'xgb_max_depth': 4, 'xgb_learning_rate': 0.1195960383019184, 'xgb_subsample': 0.8550229885420852, 'xgb_colsample_bytree': 0.9548850970305306, 'xgb_min_child_weight': 5, 'xgb_reg_alpha': 1.1921975182604538e-07, 'xgb_reg_lambda': 0.02625445968759339, 'lgbm_n_estimators': 481, 'lgbm_max_depth': 8, 'lgbm_learning_rate': 0.13766134492174428, 'lgbm_num_leaves': 70, 'lgbm_subsample': 0.8090931317527976, 'lgbm_colsample_bytree': 0.7710164073434198, 'lgbm_reg_alpha': 1.6934490731313353e-08, 'lgbm_reg_lambda': 9.354548757337708e-08, 'cat_iterations': 115, 'cat_depth': 7, 'cat_learning_rate': 0.029130095015495922, 'cat_l2_leaf_reg': 0.1082138291061399, 'meta_C': 27.886810374231203}. Best is trial 3 with value: 0.8233955388709706.

Best trial: 5. Best value: 0.825128:  12%|█▏        | 6/50 [06:35<50:38, 69.05s/it]

[I 2026-05-14 12:10:41,230] Trial 5 finished with value: 0.8251277581943757 and parameters: {'xgb_n_estimators': 274, 'xgb_max_depth': 5, 'xgb_learning_rate': 0.1306293138834092, 'xgb_subsample': 0.6915192661966489, 'xgb_colsample_bytree': 0.6307919639315172, 'xgb_min_child_weight': 3, 'xgb_reg_alpha': 2.824825241715838e-07, 'xgb_reg_lambda': 2.3295866619309256, 'lgbm_n_estimators': 504, 'lgbm_max_depth': 8, 'lgbm_learning_rate': 0.1937550186412042, 'lgbm_num_leaves': 105, 'lgbm_subsample': 0.6746280235544143, 'lgbm_colsample_bytree': 0.9570235993959911, 'lgbm_reg_alpha': 0.000714628244934021, 'lgbm_reg_lambda': 0.18491042486838075, 'cat_iterations': 548, 'cat_depth': 4, 'cat_learning_rate': 0.014539853705640319, 'cat_l2_leaf_reg': 0.008160948743089917, 'meta_C': 0.036529752669123616}. Best is trial 5 with value: 0.8251277581943757.

Best trial: 5. Best value: 0.825128:  14%|█▍        | 7/50 [07:41<48:40, 67.92s/it]

[I 2026-05-14 12:11:46,819] Trial 6 finished with value: 0.8126787493974655 and parameters: {'xgb_n_estimators': 673, 'xgb_max_depth': 9, 'xgb_learning_rate': 0.010239273411172712, 'xgb_subsample': 0.8042989210310263, 'xgb_colsample_bytree': 0.7669644012595116, 'xgb_min_child_weight': 3, 'xgb_reg_alpha': 1.1989147575590843e-07, 'xgb_reg_lambda': 1.0927895733904103e-05, 'lgbm_n_estimators': 572, 'lgbm_max_depth': 5, 'lgbm_learning_rate': 0.05838706626832953, 'lgbm_num_leaves': 94, 'lgbm_subsample': 0.7454518409517176, 'lgbm_colsample_bytree': 0.9887128330883843, 'lgbm_reg_alpha': 4.592251392089998, 'lgbm_reg_lambda': 1.845188173664121e-06, 'cat_iterations': 349, 'cat_depth': 4, 'cat_learning_rate': 0.02634777514406047, 'cat_l2_leaf_reg': 0.0014045842344024703, 'meta_C': 0.4543452623910883}. Best is trial 5 with value: 0.8251277581943757.

Best trial: 5. Best value: 0.825128:  16%|█▌        | 8/50 [08:24<41:56, 59.92s/it]

[I 2026-05-14 12:12:29,617] Trial 7 finished with value: 0.823528549296771 and parameters: {'xgb_n_estimators': 452, 'xgb_max_depth': 2, 'xgb_learning_rate': 0.025798509464504106, 'xgb_subsample': 0.9633063543866615, 'xgb_colsample_bytree': 0.695824756266789, 'xgb_min_child_weight': 2, 'xgb_reg_alpha': 0.0002541410632209718, 'xgb_reg_lambda': 7.427695424061678, 'lgbm_n_estimators': 221, 'lgbm_max_depth': 9, 'lgbm_learning_rate': 0.1333535316674426, 'lgbm_num_leaves': 41, 'lgbm_subsample': 0.8912865394447438, 'lgbm_colsample_bytree': 0.7471132530877013, 'lgbm_reg_alpha': 0.00490628164601872, 'lgbm_reg_lambda': 0.005032310118297565, 'cat_iterations': 368, 'cat_depth': 2, 'cat_learning_rate': 0.17133380914396035, 'cat_l2_leaf_reg': 0.019192001101561888, 'meta_C': 0.0013155612184703935}. Best is trial 5 with value: 0.8251277581943757.

Best trial: 5. Best value: 0.825128:  18%|█▊        | 9/50 [09:18<39:51, 58.33s/it]

[I 2026-05-14 12:13:24,458] Trial 8 finished with value: 0.8161353301032103 and parameters: {'xgb_n_estimators': 128, 'xgb_max_depth': 7, 'xgb_learning_rate': 0.10019469332296198, 'xgb_subsample': 0.6066351315711425, 'xgb_colsample_bytree': 0.8048372233197124, 'xgb_min_child_weight': 3, 'xgb_reg_alpha': 0.006405530651255316, 'xgb_reg_lambda': 3.709350405068891e-07, 'lgbm_n_estimators': 446, 'lgbm_max_depth': 6, 'lgbm_learning_rate': 0.2419155450887376, 'lgbm_num_leaves': 30, 'lgbm_subsample': 0.7364265404201034, 'lgbm_colsample_bytree': 0.6453894084962356, 'lgbm_reg_alpha': 2.100112522343288, 'lgbm_reg_lambda': 0.7871439837551527, 'cat_iterations': 229, 'cat_depth': 7, 'cat_learning_rate': 0.16111511355977057, 'cat_l2_leaf_reg': 0.16626592254031874, 'meta_C': 0.1506272232520006}. Best is trial 5 with value: 0.8251277581943757.

Best trial: 9. Best value: 0.832404:  20%|██        | 10/50 [10:24<40:23, 60.58s/it]

[I 2026-05-14 12:14:30,079] Trial 9 finished with value: 0.8324038330287843 and parameters: {'xgb_n_estimators': 269, 'xgb_max_depth': 2, 'xgb_learning_rate': 0.21149322814164553, 'xgb_subsample': 0.9601672228653322, 'xgb_colsample_bytree': 0.8532405829093072, 'xgb_min_child_weight': 4, 'xgb_reg_alpha': 1.3895883726793775e-05, 'xgb_reg_lambda': 0.03416654859330391, 'lgbm_n_estimators': 549, 'lgbm_max_depth': 11, 'lgbm_learning_rate': 0.1418961933595484, 'lgbm_num_leaves': 87, 'lgbm_subsample': 0.6336559859980195, 'lgbm_colsample_bytree': 0.6646514856378455, 'lgbm_reg_alpha': 1.2217650479327244, 'lgbm_reg_lambda': 0.0028698654570754596, 'cat_iterations': 104, 'cat_depth': 2, 'cat_learning_rate': 0.09551521678079945, 'cat_l2_leaf_reg': 0.001047722656409829, 'meta_C': 0.0009222492453004666}. Best is trial 9 with value: 0.8324038330287843.

Best trial: 9. Best value: 0.832404:  22%|██▏       | 11/50 [11:37<41:45, 64.24s/it]

[I 2026-05-14 12:15:42,610] Trial 10 finished with value: 0.821014921446032 and parameters: {'xgb_n_estimators': 598, 'xgb_max_depth': 2, 'xgb_learning_rate': 0.2704729722717776, 'xgb_subsample': 0.9819449254091989, 'xgb_colsample_bytree': 0.833236657140915, 'xgb_min_child_weight': 10, 'xgb_reg_alpha': 1.7856978181230155e-05, 'xgb_reg_lambda': 4.364557274669002e-05, 'lgbm_n_estimators': 322, 'lgbm_max_depth': 12, 'lgbm_learning_rate': 0.04945003715146827, 'lgbm_num_leaves': 64, 'lgbm_subsample': 0.6094262266054595, 'lgbm_colsample_bytree': 0.6216254354281846, 'lgbm_reg_alpha': 1.2096060313323957e-05, 'lgbm_reg_lambda': 0.0007522249733932725, 'cat_iterations': 592, 'cat_depth': 2, 'cat_learning_rate': 0.09594334971245233, 'cat_l2_leaf_reg': 3.7639965874723003, 'meta_C': 0.0038143603969884913}. Best is trial 9 with value: 0.8324038330287843.

Best trial: 9. Best value: 0.832404:  24%|██▍       | 12/50 [13:26<49:26, 78.07s/it]

[I 2026-05-14 12:17:32,310] Trial 11 finished with value: 0.829067324554333 and parameters: {'xgb_n_estimators': 251, 'xgb_max_depth': 6, 'xgb_learning_rate': 0.24678737483385346, 'xgb_subsample': 0.7390533721986331, 'xgb_colsample_bytree': 0.6134343539737889, 'xgb_min_child_weight': 5, 'xgb_reg_alpha': 1.2167282577786403e-05, 'xgb_reg_lambda': 7.782386500828553, 'lgbm_n_estimators': 511, 'lgbm_max_depth': 12, 'lgbm_learning_rate': 0.07306768063976761, 'lgbm_num_leaves': 96, 'lgbm_subsample': 0.6156780437366363, 'lgbm_colsample_bytree': 0.8646536384053466, 'lgbm_reg_alpha': 0.003405286095716241, 'lgbm_reg_lambda': 0.1056658109496573, 'cat_iterations': 583, 'cat_depth': 4, 'cat_learning_rate': 0.012652560872927359, 'cat_l2_leaf_reg': 0.0012970725768291322, 'meta_C': 0.007547115503098326}. Best is trial 9 with value: 0.8324038330287843.

Best trial: 9. Best value: 0.832404:  26%|██▌       | 13/50 [14:46<48:31, 78.68s/it]

[I 2026-05-14 12:18:52,386] Trial 12 finished with value: 0.829597039256252 and parameters: {'xgb_n_estimators': 491, 'xgb_max_depth': 7, 'xgb_learning_rate': 0.2405601802643519, 'xgb_subsample': 0.7539796407337818, 'xgb_colsample_bytree': 0.8616579277666834, 'xgb_min_child_weight': 6, 'xgb_reg_alpha': 8.72520957340892e-06, 'xgb_reg_lambda': 0.00478373962543014, 'lgbm_n_estimators': 339, 'lgbm_max_depth': 12, 'lgbm_learning_rate': 0.07942383092448925, 'lgbm_num_leaves': 85, 'lgbm_subsample': 0.6018960478612357, 'lgbm_colsample_bytree': 0.8539823580979596, 'lgbm_reg_alpha': 0.05922870673843078, 'lgbm_reg_lambda': 0.01969145286885933, 'cat_iterations': 482, 'cat_depth': 3, 'cat_learning_rate': 0.010030113323163933, 'cat_l2_leaf_reg': 0.001284920048900095, 'meta_C': 0.005621901465083751}. Best is trial 9 with value: 0.8324038330287843.

Best trial: 9. Best value: 0.832404:  28%|██▊       | 14/50 [15:50<44:32, 74.25s/it]

[I 2026-05-14 12:19:56,397] Trial 13 finished with value: 0.8317992366878647 and parameters: {'xgb_n_estimators': 520, 'xgb_max_depth': 8, 'xgb_learning_rate': 0.19459811527872142, 'xgb_subsample': 0.9232726187625369, 'xgb_colsample_bytree': 0.8695572430301038, 'xgb_min_child_weight': 7, 'xgb_reg_alpha': 5.6588245132182865e-06, 'xgb_reg_lambda': 0.0016727153700374284, 'lgbm_n_estimators': 327, 'lgbm_max_depth': 11, 'lgbm_learning_rate': 0.08609119860957623, 'lgbm_num_leaves': 57, 'lgbm_subsample': 0.6592876646576478, 'lgbm_colsample_bytree': 0.8416634198004797, 'lgbm_reg_alpha': 0.07361199805247857, 'lgbm_reg_lambda': 0.007515571723249142, 'cat_iterations': 445, 'cat_depth': 2, 'cat_learning_rate': 0.2645969367790508, 'cat_l2_leaf_reg': 1.3113324528089363, 'meta_C': 0.0001305485034563347}. Best is trial 9 with value: 0.8324038330287843.

Best trial: 9. Best value: 0.832404:  30%|███       | 15/50 [17:11<44:21, 76.04s/it]

[I 2026-05-14 12:21:16,595] Trial 14 finished with value: 0.8303206209896092 and parameters: {'xgb_n_estimators': 794, 'xgb_max_depth': 8, 'xgb_learning_rate': 0.16064382213770606, 'xgb_subsample': 0.9228654332400228, 'xgb_colsample_bytree': 0.9988197014498457, 'xgb_min_child_weight': 8, 'xgb_reg_alpha': 0.13382476826794112, 'xgb_reg_lambda': 0.00022076940080093912, 'lgbm_n_estimators': 284, 'lgbm_max_depth': 10, 'lgbm_learning_rate': 0.03535905461216466, 'lgbm_num_leaves': 54, 'lgbm_subsample': 0.6777883289584227, 'lgbm_colsample_bytree': 0.7111840499385248, 'lgbm_reg_alpha': 0.13820037589076328, 'lgbm_reg_lambda': 0.00015412282482000833, 'cat_iterations': 430, 'cat_depth': 2, 'cat_learning_rate': 0.26421867730647425, 'cat_l2_leaf_reg': 0.8520830560571354, 'meta_C': 0.00012103713079640799}. Best is trial 9 with value: 0.8324038330287843.

Best trial: 9. Best value: 0.832404:  32%|███▏      | 16/50 [19:52<57:43, 101.86s/it]

[I 2026-05-14 12:23:58,418] Trial 15 finished with value: 0.8306563577847049 and parameters: {'xgb_n_estimators': 532, 'xgb_max_depth': 8, 'xgb_learning_rate': 0.06782181176718569, 'xgb_subsample': 0.9107700647351253, 'xgb_colsample_bytree': 0.8691818178904136, 'xgb_min_child_weight': 8, 'xgb_reg_alpha': 3.6606164235209046e-06, 'xgb_reg_lambda': 0.0018168441686440624, 'lgbm_n_estimators': 398, 'lgbm_max_depth': 11, 'lgbm_learning_rate': 0.10449774094005482, 'lgbm_num_leaves': 51, 'lgbm_subsample': 0.6773024798205879, 'lgbm_colsample_bytree': 0.8232385600864432, 'lgbm_reg_alpha': 9.255127715234593, 'lgbm_reg_lambda': 9.85465202783269, 'cat_iterations': 310, 'cat_depth': 10, 'cat_learning_rate': 0.28594929857368, 'cat_l2_leaf_reg': 6.75074472390533, 'meta_C': 0.0006923003627904941}. Best is trial 9 with value: 0.8324038330287843.

Best trial: 9. Best value: 0.832404:  34%|███▍      | 17/50 [20:47<48:11, 87.63s/it]

[I 2026-05-14 12:24:52,960] Trial 16 finished with value: 0.8231060301827455 and parameters: {'xgb_n_estimators': 396, 'xgb_max_depth': 3, 'xgb_learning_rate': 0.1675629037403375, 'xgb_subsample': 0.9961915964227763, 'xgb_colsample_bytree': 0.7680901716968906, 'xgb_min_child_weight': 8, 'xgb_reg_alpha': 1.9472669965661167e-06, 'xgb_reg_lambda': 0.06776674903228322, 'lgbm_n_estimators': 258, 'lgbm_max_depth': 4, 'lgbm_learning_rate': 0.0331941215540008, 'lgbm_num_leaves': 78, 'lgbm_subsample': 0.7405114480881256, 'lgbm_colsample_bytree': 0.7890802840655012, 'lgbm_reg_alpha': 1.6970347884553177e-05, 'lgbm_reg_lambda': 0.0002007939346419182, 'cat_iterations': 464, 'cat_depth': 5, 'cat_learning_rate': 0.0818130585342663, 'cat_l2_leaf_reg': 0.5617414823719047, 'meta_C': 0.0001355270614155164}. Best is trial 9 with value: 0.8324038330287843.

Best trial: 9. Best value: 0.832404:  36%|███▌      | 18/50 [22:07<45:34, 85.46s/it]

[I 2026-05-14 12:26:13,375] Trial 17 finished with value: 0.8294988836476584 and parameters: {'xgb_n_estimators': 662, 'xgb_max_depth': 6, 'xgb_learning_rate': 0.08407274983689922, 'xgb_subsample': 0.91060801995418, 'xgb_colsample_bytree': 0.8856902915291804, 'xgb_min_child_weight': 7, 'xgb_reg_alpha': 8.004787547021148e-05, 'xgb_reg_lambda': 6.3591920508955415e-06, 'lgbm_n_estimators': 386, 'lgbm_max_depth': 10, 'lgbm_learning_rate': 0.09415305418338754, 'lgbm_num_leaves': 64, 'lgbm_subsample': 0.6445717557592572, 'lgbm_colsample_bytree': 0.7280368580262182, 'lgbm_reg_alpha': 0.02231386393086231, 'lgbm_reg_lambda': 0.0025160034631991055, 'cat_iterations': 406, 'cat_depth': 3, 'cat_learning_rate': 0.13660264251522405, 'cat_l2_leaf_reg': 1.6164452331618713, 'meta_C': 0.000870278777399649}. Best is trial 9 with value: 0.8324038330287843.

Best trial: 9. Best value: 0.832404:  38%|███▊      | 19/50 [22:49<37:23, 72.37s/it]

[I 2026-05-14 12:26:55,226] Trial 18 finished with value: 0.8172446603851778 and parameters: {'xgb_n_estimators': 545, 'xgb_max_depth': 8, 'xgb_learning_rate': 0.04046737857296407, 'xgb_subsample': 0.9446612462274991, 'xgb_colsample_bytree': 0.8051973906745902, 'xgb_min_child_weight': 4, 'xgb_reg_alpha': 0.0037972928065593907, 'xgb_reg_lambda': 0.0002609910744714821, 'lgbm_n_estimators': 145, 'lgbm_max_depth': 11, 'lgbm_learning_rate': 0.03862154153587166, 'lgbm_num_leaves': 45, 'lgbm_subsample': 0.7232364547166343, 'lgbm_colsample_bytree': 0.6735633858134757, 'lgbm_reg_alpha': 0.6638789951784873, 'lgbm_reg_lambda': 4.484792995298011e-05, 'cat_iterations': 230, 'cat_depth': 3, 'cat_learning_rate': 0.06540560701351561, 'cat_l2_leaf_reg': 0.2690023191222379, 'meta_C': 0.018929144752244838}. Best is trial 9 with value: 0.8324038330287843.

Best trial: 9. Best value: 0.832404:  40%|████      | 20/50 [24:25<39:46, 79.56s/it]

[I 2026-05-14 12:28:31,556] Trial 19 finished with value: 0.8278284032214657 and parameters: {'xgb_n_estimators': 418, 'xgb_max_depth': 5, 'xgb_learning_rate': 0.18906856171763672, 'xgb_subsample': 0.8810331712700826, 'xgb_colsample_bytree': 0.9595549848131131, 'xgb_min_child_weight': 10, 'xgb_reg_alpha': 1.2802126258933879e-08, 'xgb_reg_lambda': 1.1717491750691429e-08, 'lgbm_n_estimators': 547, 'lgbm_max_depth': 7, 'lgbm_learning_rate': 0.021793190071613802, 'lgbm_num_leaves': 80, 'lgbm_subsample': 0.7010164050257928, 'lgbm_colsample_bytree': 0.6023955458032627, 'lgbm_reg_alpha': 6.609317633115774e-05, 'lgbm_reg_lambda': 1.3988079666240726e-08, 'cat_iterations': 502, 'cat_depth': 6, 'cat_learning_rate': 0.21889204612479898, 'cat_l2_leaf_reg': 2.184006880220188, 'meta_C': 0.0004392939966201468}. Best is trial 9 with value: 0.8324038330287843.

Best trial: 20. Best value: 0.834497:  42%|████▏     | 21/50 [26:11<42:13, 87.35s/it]

[I 2026-05-14 12:30:17,074] Trial 20 finished with value: 0.8344970920012262 and parameters: {'xgb_n_estimators': 217, 'xgb_max_depth': 9, 'xgb_learning_rate': 0.013908945829988006, 'xgb_subsample': 0.9465722368419314, 'xgb_colsample_bytree': 0.8398791891853424, 'xgb_min_child_weight': 7, 'xgb_reg_alpha': 8.558681444281539e-07, 'xgb_reg_lambda': 0.2748644039077037, 'lgbm_n_estimators': 453, 'lgbm_max_depth': 11, 'lgbm_learning_rate': 0.10788845009630893, 'lgbm_num_leaves': 109, 'lgbm_subsample': 0.7830693031226539, 'lgbm_colsample_bytree': 0.9072988320968839, 'lgbm_reg_alpha': 0.538604280335804, 'lgbm_reg_lambda': 0.04900377161863826, 'cat_iterations': 290, 'cat_depth': 5, 'cat_learning_rate': 0.1169546605715017, 'cat_l2_leaf_reg': 0.04742725604473912, 'meta_C': 0.0022518946044980583}. Best is trial 20 with value: 0.8344970920012262.

Best trial: 21. Best value: 0.835295:  44%|████▍     | 22/50 [27:41<41:06, 88.07s/it]

[I 2026-05-14 12:31:46,825] Trial 21 finished with value: 0.8352947779544427 and parameters: {'xgb_n_estimators': 193, 'xgb_max_depth': 9, 'xgb_learning_rate': 0.01052220133228744, 'xgb_subsample': 0.9532781721312175, 'xgb_colsample_bytree': 0.8288930672316205, 'xgb_min_child_weight': 7, 'xgb_reg_alpha': 5.887192903515314e-07, 'xgb_reg_lambda': 0.4491222367310672, 'lgbm_n_estimators': 454, 'lgbm_max_depth': 11, 'lgbm_learning_rate': 0.10448930759061142, 'lgbm_num_leaves': 106, 'lgbm_subsample': 0.7864414258734168, 'lgbm_colsample_bytree': 0.914671098933821, 'lgbm_reg_alpha': 0.5748643553148517, 'lgbm_reg_lambda': 0.034378144497738954, 'cat_iterations': 292, 'cat_depth': 5, 'cat_learning_rate': 0.11539732870459508, 'cat_l2_leaf_reg': 0.0464982380468516, 'meta_C': 0.0013149297495986597}. Best is trial 21 with value: 0.8352947779544427.

Best trial: 22. Best value: 0.835492:  46%|████▌     | 23/50 [29:13<40:14, 89.43s/it]

[I 2026-05-14 12:33:19,412] Trial 22 finished with value: 0.8354918779124436 and parameters: {'xgb_n_estimators': 197, 'xgb_max_depth': 9, 'xgb_learning_rate': 0.012291287105618928, 'xgb_subsample': 0.9982748467361235, 'xgb_colsample_bytree': 0.8242774121894533, 'xgb_min_child_weight': 7, 'xgb_reg_alpha': 5.429041527337054e-07, 'xgb_reg_lambda': 0.34997302897432886, 'lgbm_n_estimators': 436, 'lgbm_max_depth': 11, 'lgbm_learning_rate': 0.12636612028183597, 'lgbm_num_leaves': 111, 'lgbm_subsample': 0.7863973351578589, 'lgbm_colsample_bytree': 0.9091198478652761, 'lgbm_reg_alpha': 0.7593357795891027, 'lgbm_reg_lambda': 0.09384423689945098, 'cat_iterations': 264, 'cat_depth': 5, 'cat_learning_rate': 0.11095111657952873, 'cat_l2_leaf_reg': 0.052742507909932845, 'meta_C': 0.00194262580816405}. Best is trial 22 with value: 0.8354918779124436.

Best trial: 22. Best value: 0.835492:  48%|████▊     | 24/50 [30:32<37:19, 86.13s/it]

[I 2026-05-14 12:34:37,840] Trial 23 finished with value: 0.8334893645900706 and parameters: {'xgb_n_estimators': 182, 'xgb_max_depth': 9, 'xgb_learning_rate': 0.010523402399108367, 'xgb_subsample': 0.9927966716888034, 'xgb_colsample_bytree': 0.7517158276445217, 'xgb_min_child_weight': 9, 'xgb_reg_alpha': 6.774800937757393e-07, 'xgb_reg_lambda': 0.49034112117120077, 'lgbm_n_estimators': 455, 'lgbm_max_depth': 9, 'lgbm_learning_rate': 0.2975247236877044, 'lgbm_num_leaves': 109, 'lgbm_subsample': 0.7863822613981469, 'lgbm_colsample_bytree': 0.9124592968397294, 'lgbm_reg_alpha': 0.006831971605634746, 'lgbm_reg_lambda': 2.000374757533962, 'cat_iterations': 294, 'cat_depth': 5, 'cat_learning_rate': 0.1254175717948688, 'cat_l2_leaf_reg': 0.04371199967454616, 'meta_C': 0.0035263363852739435}. Best is trial 22 with value: 0.8354918779124436.

Best trial: 22. Best value: 0.835492:  50%|█████     | 25/50 [32:01<36:13, 86.94s/it]

[I 2026-05-14 12:36:06,685] Trial 24 finished with value: 0.8297258992973695 and parameters: {'xgb_n_estimators': 198, 'xgb_max_depth': 9, 'xgb_learning_rate': 0.015025995884144043, 'xgb_subsample': 0.8920996894929094, 'xgb_colsample_bytree': 0.8188911135000535, 'xgb_min_child_weight': 7, 'xgb_reg_alpha': 6.744976488442841e-07, 'xgb_reg_lambda': 0.49572361219192385, 'lgbm_n_estimators': 434, 'lgbm_max_depth': 10, 'lgbm_learning_rate': 0.11705214797691912, 'lgbm_num_leaves': 121, 'lgbm_subsample': 0.7910369072479406, 'lgbm_colsample_bytree': 0.8988193601240352, 'lgbm_reg_alpha': 0.6189020030693058, 'lgbm_reg_lambda': 0.0788657332990496, 'cat_iterations': 283, 'cat_depth': 5, 'cat_learning_rate': 0.06303517947534658, 'cat_l2_leaf_reg': 0.04786743532991413, 'meta_C': 0.011631869130172404}. Best is trial 22 with value: 0.8354918779124436.

Best trial: 22. Best value: 0.835492:  52%|█████▏    | 26/50 [33:13<33:04, 82.69s/it]

[I 2026-05-14 12:37:19,445] Trial 25 finished with value: 0.8305522002681052 and parameters: {'xgb_n_estimators': 115, 'xgb_max_depth': 10, 'xgb_learning_rate': 0.01644060958024508, 'xgb_subsample': 0.9433481938257343, 'xgb_colsample_bytree': 0.7790646518649741, 'xgb_min_child_weight': 9, 'xgb_reg_alpha': 6.287891369248924e-08, 'xgb_reg_lambda': 0.18394492572021187, 'lgbm_n_estimators': 381, 'lgbm_max_depth': 12, 'lgbm_learning_rate': 0.06380099634078691, 'lgbm_num_leaves': 107, 'lgbm_subsample': 0.8425833772428869, 'lgbm_colsample_bytree': 0.9318445565813331, 'lgbm_reg_alpha': 0.0006736473497275116, 'lgbm_reg_lambda': 0.025526127896972627, 'cat_iterations': 199, 'cat_depth': 6, 'cat_learning_rate': 0.11563866105468484, 'cat_l2_leaf_reg': 0.05602265006952131, 'meta_C': 0.0024103276583917897}. Best is trial 22 with value: 0.8354918779124436.

Best trial: 22. Best value: 0.835492:  54%|█████▍    | 27/50 [34:55<33:55, 88.49s/it]

[I 2026-05-14 12:39:01,470] Trial 26 finished with value: 0.8264543351070357 and parameters: {'xgb_n_estimators': 222, 'xgb_max_depth': 9, 'xgb_learning_rate': 0.01425479591263619, 'xgb_subsample': 0.835007027266648, 'xgb_colsample_bytree': 0.8321047860888015, 'xgb_min_child_weight': 6, 'xgb_reg_alpha': 6.47560568827685e-05, 'xgb_reg_lambda': 0.010893230793866534, 'lgbm_n_estimators': 480, 'lgbm_max_depth': 11, 'lgbm_learning_rate': 0.18640786833751058, 'lgbm_num_leaves': 114, 'lgbm_subsample': 0.8300295282705031, 'lgbm_colsample_bytree': 0.8799957244044438, 'lgbm_reg_alpha': 0.32992171476494747, 'lgbm_reg_lambda': 0.6328175521507107, 'cat_iterations': 340, 'cat_depth': 5, 'cat_learning_rate': 0.1917502805382735, 'cat_l2_leaf_reg': 0.2723646469711475, 'meta_C': 0.020838860067057305}. Best is trial 22 with value: 0.8354918779124436.

Best trial: 22. Best value: 0.835492:  56%|█████▌    | 28/50 [36:02<30:01, 81.87s/it]

[I 2026-05-14 12:40:07,891] Trial 27 finished with value: 0.8156442649493296 and parameters: {'xgb_n_estimators': 306, 'xgb_max_depth': 7, 'xgb_learning_rate': 0.021829082052278407, 'xgb_subsample': 0.9730321729914481, 'xgb_colsample_bytree': 0.9036642100549287, 'xgb_min_child_weight': 7, 'xgb_reg_alpha': 9.774379972340776e-07, 'xgb_reg_lambda': 2.4559246043085263, 'lgbm_n_estimators': 419, 'lgbm_max_depth': 7, 'lgbm_learning_rate': 0.10047996476077642, 'lgbm_num_leaves': 100, 'lgbm_subsample': 0.7692995902414984, 'lgbm_colsample_bytree': 0.9451031020343202, 'lgbm_reg_alpha': 9.56398652821831, 'lgbm_reg_lambda': 4.099905750913723, 'cat_iterations': 386, 'cat_depth': 7, 'cat_learning_rate': 0.14188103830563267, 'cat_l2_leaf_reg': 0.007280789631178693, 'meta_C': 0.05387444516207404}. Best is trial 22 with value: 0.8354918779124436.

Best trial: 22. Best value: 0.835492:  58%|█████▊    | 29/50 [36:35<23:32, 67.28s/it]

[I 2026-05-14 12:40:41,125] Trial 28 finished with value: 0.8262439642540473 and parameters: {'xgb_n_estimators': 154, 'xgb_max_depth': 10, 'xgb_learning_rate': 0.012726434137581124, 'xgb_subsample': 0.9998190251068291, 'xgb_colsample_bytree': 0.730545209030808, 'xgb_min_child_weight': 9, 'xgb_reg_alpha': 2.919681989704712e-07, 'xgb_reg_lambda': 1.1280756721329372, 'lgbm_n_estimators': 513, 'lgbm_max_depth': 3, 'lgbm_learning_rate': 0.179745823979427, 'lgbm_num_leaves': 126, 'lgbm_subsample': 0.8811866570853557, 'lgbm_colsample_bytree': 0.8067004616295494, 'lgbm_reg_alpha': 0.03598833483581132, 'lgbm_reg_lambda': 0.36072272058082405, 'cat_iterations': 190, 'cat_depth': 5, 'cat_learning_rate': 0.1098296474514627, 'cat_l2_leaf_reg': 0.07939724864016715, 'meta_C': 0.0003271770276959321}. Best is trial 22 with value: 0.8354918779124436.

Best trial: 22. Best value: 0.835492:  60%|██████    | 30/50 [37:45<22:38, 67.94s/it]

[I 2026-05-14 12:41:50,596] Trial 29 finished with value: 0.814874195317189 and parameters: {'xgb_n_estimators': 352, 'xgb_max_depth': 9, 'xgb_learning_rate': 0.017272487703303474, 'xgb_subsample': 0.8311734474597696, 'xgb_colsample_bytree': 0.7886334943731855, 'xgb_min_child_weight': 8, 'xgb_reg_alpha': 1.806599621997086e-08, 'xgb_reg_lambda': 0.28431497320934535, 'lgbm_n_estimators': 361, 'lgbm_max_depth': 9, 'lgbm_learning_rate': 0.046595133437879424, 'lgbm_num_leaves': 115, 'lgbm_subsample': 0.7659333862194391, 'lgbm_colsample_bytree': 0.8903290997603761, 'lgbm_reg_alpha': 0.013330914382209421, 'lgbm_reg_lambda': 0.06792905902108985, 'cat_iterations': 262, 'cat_depth': 6, 'cat_learning_rate': 0.05402569921766632, 'cat_l2_leaf_reg': 0.033845418981821425, 'meta_C': 0.3831177770803474}. Best is trial 22 with value: 0.8354918779124436.

Best trial: 22. Best value: 0.835492:  62%|██████▏   | 31/50 [39:41<26:07, 82.49s/it]

[I 2026-05-14 12:43:47,058] Trial 30 finished with value: 0.8128374412932683 and parameters: {'xgb_n_estimators': 235, 'xgb_max_depth': 10, 'xgb_learning_rate': 0.032904348059070276, 'xgb_subsample': 0.9538116529254702, 'xgb_colsample_bytree': 0.6674226270693864, 'xgb_min_child_weight': 5, 'xgb_reg_alpha': 3.1805371260408046e-08, 'xgb_reg_lambda': 0.009862701105857824, 'lgbm_n_estimators': 471, 'lgbm_max_depth': 10, 'lgbm_learning_rate': 0.011562753397160095, 'lgbm_num_leaves': 126, 'lgbm_subsample': 0.8149538225411991, 'lgbm_colsample_bytree': 0.9171054278053732, 'lgbm_reg_alpha': 2.2763750977223625, 'lgbm_reg_lambda': 0.021099017359323544, 'cat_iterations': 320, 'cat_depth': 8, 'cat_learning_rate': 0.07890747692804433, 'cat_l2_leaf_reg': 0.004361605472601164, 'meta_C': 3.94488878308695}. Best is trial 22 with value: 0.8354918779124436.

Best trial: 22. Best value: 0.835492:  64%|██████▍   | 32/50 [40:58<24:16, 80.91s/it]

[I 2026-05-14 12:45:04,254] Trial 31 finished with value: 0.8333945990949191 and parameters: {'xgb_n_estimators': 167, 'xgb_max_depth': 9, 'xgb_learning_rate': 0.010752962429151039, 'xgb_subsample': 0.9991613164008712, 'xgb_colsample_bytree': 0.8336707756401011, 'xgb_min_child_weight': 9, 'xgb_reg_alpha': 2.3353583490454348e-07, 'xgb_reg_lambda': 0.5457119368792313, 'lgbm_n_estimators': 448, 'lgbm_max_depth': 9, 'lgbm_learning_rate': 0.2907599377526449, 'lgbm_num_leaves': 107, 'lgbm_subsample': 0.7780723272340013, 'lgbm_colsample_bytree': 0.9356683100984658, 'lgbm_reg_alpha': 0.00388791481854581, 'lgbm_reg_lambda': 2.008563099348133, 'cat_iterations': 286, 'cat_depth': 5, 'cat_learning_rate': 0.13479641004522266, 'cat_l2_leaf_reg': 0.0322853002770926, 'meta_C': 0.0023130519680860636}. Best is trial 22 with value: 0.8354918779124436.

Best trial: 22. Best value: 0.835492:  66%|██████▌   | 33/50 [42:02<21:29, 75.88s/it]

[I 2026-05-14 12:46:08,405] Trial 32 finished with value: 0.8324789401433618 and parameters: {'xgb_n_estimators': 183, 'xgb_max_depth': 8, 'xgb_learning_rate': 0.01974644754833665, 'xgb_subsample': 0.9281923265932441, 'xgb_colsample_bytree': 0.7356908294842233, 'xgb_min_child_weight': 9, 'xgb_reg_alpha': 5.423213797976002e-07, 'xgb_reg_lambda': 0.15480470757197928, 'lgbm_n_estimators': 432, 'lgbm_max_depth': 8, 'lgbm_learning_rate': 0.2989994393715067, 'lgbm_num_leaves': 110, 'lgbm_subsample': 0.8543877538923174, 'lgbm_colsample_bytree': 0.8642804288303793, 'lgbm_reg_alpha': 0.15056950733616256, 'lgbm_reg_lambda': 1.6984519768710893, 'cat_iterations': 244, 'cat_depth': 6, 'cat_learning_rate': 0.20672931469032368, 'cat_l2_leaf_reg': 0.10985319733157525, 'meta_C': 0.0016674743860571116}. Best is trial 22 with value: 0.8354918779124436.

Best trial: 22. Best value: 0.835492:  68%|██████▊   | 34/50 [43:17<20:06, 75.42s/it]

[I 2026-05-14 12:47:22,746] Trial 33 finished with value: 0.8347311770479109 and parameters: {'xgb_n_estimators': 101, 'xgb_max_depth': 9, 'xgb_learning_rate': 0.011568062171392484, 'xgb_subsample': 0.97485631082554, 'xgb_colsample_bytree': 0.750992149597631, 'xgb_min_child_weight': 6, 'xgb_reg_alpha': 1.5964035236429711e-06, 'xgb_reg_lambda': 2.291668293574967, 'lgbm_n_estimators': 414, 'lgbm_max_depth': 10, 'lgbm_learning_rate': 0.22667398090902274, 'lgbm_num_leaves': 101, 'lgbm_subsample': 0.7920823415420716, 'lgbm_colsample_bytree': 0.999474988385968, 'lgbm_reg_alpha': 0.5400271614125377, 'lgbm_reg_lambda': 0.0007158061824437186, 'cat_iterations': 299, 'cat_depth': 4, 'cat_learning_rate': 0.10577023343821026, 'cat_l2_leaf_reg': 0.2273477583054685, 'meta_C': 0.004879097860388084}. Best is trial 22 with value: 0.8354918779124436.

Best trial: 22. Best value: 0.835492:  70%|███████   | 35/50 [44:34<19:01, 76.12s/it]

[I 2026-05-14 12:48:40,503] Trial 34 finished with value: 0.8331555674635279 and parameters: {'xgb_n_estimators': 104, 'xgb_max_depth': 10, 'xgb_learning_rate': 0.013091746198578393, 'xgb_subsample': 0.8751827813716859, 'xgb_colsample_bytree': 0.7079216502442958, 'xgb_min_child_weight': 6, 'xgb_reg_alpha': 1.6432906065177695e-06, 'xgb_reg_lambda': 2.8227202601477037, 'lgbm_n_estimators': 411, 'lgbm_max_depth': 11, 'lgbm_learning_rate': 0.23151846780415536, 'lgbm_num_leaves': 100, 'lgbm_subsample': 0.9444580598986719, 'lgbm_colsample_bytree': 0.9740666840673642, 'lgbm_reg_alpha': 0.34485382180898566, 'lgbm_reg_lambda': 0.0009611663931323068, 'cat_iterations': 267, 'cat_depth': 4, 'cat_learning_rate': 0.05448697847912545, 'cat_l2_leaf_reg': 0.24505997499946466, 'meta_C': 0.01071536109561146}. Best is trial 22 with value: 0.8354918779124436.

Best trial: 22. Best value: 0.835492:  72%|███████▏  | 36/50 [45:49<17:38, 75.61s/it]

[I 2026-05-14 12:49:54,916] Trial 35 finished with value: 0.8295603163686016 and parameters: {'xgb_n_estimators': 306, 'xgb_max_depth': 9, 'xgb_learning_rate': 0.012311007370107334, 'xgb_subsample': 0.8971908907855407, 'xgb_colsample_bytree': 0.9280450696751026, 'xgb_min_child_weight': 7, 'xgb_reg_alpha': 5.539890107815363e-05, 'xgb_reg_lambda': 9.882841877448195, 'lgbm_n_estimators': 372, 'lgbm_max_depth': 12, 'lgbm_learning_rate': 0.12187492619468639, 'lgbm_num_leaves': 119, 'lgbm_subsample': 0.8649850611854303, 'lgbm_colsample_bytree': 0.9970451402134491, 'lgbm_reg_alpha': 2.231021576925152, 'lgbm_reg_lambda': 0.0008063513183505963, 'cat_iterations': 205, 'cat_depth': 4, 'cat_learning_rate': 0.03932335655663529, 'cat_l2_leaf_reg': 0.012603757406452433, 'meta_C': 0.00039174021830649616}. Best is trial 22 with value: 0.8354918779124436.

Best trial: 22. Best value: 0.835492:  74%|███████▍  | 37/50 [47:24<17:37, 81.35s/it]

[I 2026-05-14 12:51:29,674] Trial 36 finished with value: 0.823553013927419 and parameters: {'xgb_n_estimators': 215, 'xgb_max_depth': 8, 'xgb_learning_rate': 0.028149869570345553, 'xgb_subsample': 0.9654015078717493, 'xgb_colsample_bytree': 0.7949160684302512, 'xgb_min_child_weight': 6, 'xgb_reg_alpha': 4.43822534646523e-08, 'xgb_reg_lambda': 0.03635991307601688, 'lgbm_n_estimators': 535, 'lgbm_max_depth': 10, 'lgbm_learning_rate': 0.15230589626695756, 'lgbm_num_leaves': 89, 'lgbm_subsample': 0.8101108108368303, 'lgbm_colsample_bytree': 0.9606336626575315, 'lgbm_reg_alpha': 0.23951249383424345, 'lgbm_reg_lambda': 4.5080289113896224e-05, 'cat_iterations': 356, 'cat_depth': 3, 'cat_learning_rate': 0.09990781457745328, 'cat_l2_leaf_reg': 0.4291053098594146, 'meta_C': 0.10433247893126107}. Best is trial 22 with value: 0.8354918779124436.

Best trial: 22. Best value: 0.835492:  76%|███████▌  | 38/50 [48:40<15:58, 79.90s/it]

[I 2026-05-14 12:52:46,196] Trial 37 finished with value: 0.8280974197744788 and parameters: {'xgb_n_estimators': 137, 'xgb_max_depth': 7, 'xgb_learning_rate': 0.018152709157196502, 'xgb_subsample': 0.9415806868066215, 'xgb_colsample_bytree': 0.6726527812516694, 'xgb_min_child_weight': 5, 'xgb_reg_alpha': 3.0383399273236783e-06, 'xgb_reg_lambda': 1.4273675566124608, 'lgbm_n_estimators': 296, 'lgbm_max_depth': 10, 'lgbm_learning_rate': 0.2143557838509217, 'lgbm_num_leaves': 102, 'lgbm_subsample': 0.9174747553871878, 'lgbm_colsample_bytree': 0.999967487249242, 'lgbm_reg_alpha': 0.8721022625047875, 'lgbm_reg_lambda': 0.010434770530362684, 'cat_iterations': 323, 'cat_depth': 7, 'cat_learning_rate': 0.07471972620194144, 'cat_l2_leaf_reg': 0.1348138474749186, 'meta_C': 0.02311288816574437}. Best is trial 22 with value: 0.8354918779124436.

Best trial: 22. Best value: 0.835492:  78%|███████▊  | 39/50 [50:21<15:48, 86.25s/it]

[I 2026-05-14 12:54:27,259] Trial 38 finished with value: 0.83246636517971 and parameters: {'xgb_n_estimators': 287, 'xgb_max_depth': 10, 'xgb_learning_rate': 0.04120502413429614, 'xgb_subsample': 0.8575643011127367, 'xgb_colsample_bytree': 0.750569797607548, 'xgb_min_child_weight': 7, 'xgb_reg_alpha': 1.1172173050356551e-07, 'xgb_reg_lambda': 0.13123127576577617, 'lgbm_n_estimators': 490, 'lgbm_max_depth': 11, 'lgbm_learning_rate': 0.17293455932181243, 'lgbm_num_leaves': 114, 'lgbm_subsample': 0.7629255364191527, 'lgbm_colsample_bytree': 0.9689299889207438, 'lgbm_reg_alpha': 2.7620882609885757e-07, 'lgbm_reg_lambda': 0.19107019443426693, 'cat_iterations': 388, 'cat_depth': 5, 'cat_learning_rate': 0.027747966525069938, 'cat_l2_leaf_reg': 0.0729496928658591, 'meta_C': 0.004806494653886917}. Best is trial 22 with value: 0.8354918779124436.

Best trial: 22. Best value: 0.835492:  80%|████████  | 40/50 [51:19<12:58, 77.85s/it]

[I 2026-05-14 12:55:25,508] Trial 39 finished with value: 0.811628675583064 and parameters: {'xgb_n_estimators': 161, 'xgb_max_depth': 9, 'xgb_learning_rate': 0.02078589679315258, 'xgb_subsample': 0.9776492865323521, 'xgb_colsample_bytree': 0.8186718796358667, 'xgb_min_child_weight': 6, 'xgb_reg_alpha': 6.170037042476505, 'xgb_reg_lambda': 2.788044662553328, 'lgbm_n_estimators': 408, 'lgbm_max_depth': 8, 'lgbm_learning_rate': 0.06956988469341953, 'lgbm_num_leaves': 93, 'lgbm_subsample': 0.7135917451401145, 'lgbm_colsample_bytree': 0.831692042076156, 'lgbm_reg_alpha': 3.952947598476519, 'lgbm_reg_lambda': 0.0022054339442045255, 'cat_iterations': 155, 'cat_depth': 6, 'cat_learning_rate': 0.16525260780421738, 'cat_l2_leaf_reg': 0.02202703779535996, 'meta_C': 3.442771712969493}. Best is trial 22 with value: 0.8354918779124436.

Best trial: 22. Best value: 0.835492:  82%|████████▏ | 41/50 [52:25<11:07, 74.12s/it]

[I 2026-05-14 12:56:30,938] Trial 40 finished with value: 0.8316492113398175 and parameters: {'xgb_n_estimators': 332, 'xgb_max_depth': 7, 'xgb_learning_rate': 0.010165021763275753, 'xgb_subsample': 0.6862245224710062, 'xgb_colsample_bytree': 0.8910675500625739, 'xgb_min_child_weight': 4, 'xgb_reg_alpha': 0.0019572420131679746, 'xgb_reg_lambda': 0.017453331209220952, 'lgbm_n_estimators': 573, 'lgbm_max_depth': 6, 'lgbm_learning_rate': 0.15290992057911687, 'lgbm_num_leaves': 119, 'lgbm_subsample': 0.8321125290382744, 'lgbm_colsample_bytree': 0.9298015437669059, 'lgbm_reg_alpha': 0.08101152776107658, 'lgbm_reg_lambda': 8.129260604048054e-06, 'cat_iterations': 219, 'cat_depth': 8, 'cat_learning_rate': 0.04570718044426164, 'cat_l2_leaf_reg': 0.16281096083769725, 'meta_C': 0.0012135711437566191}. Best is trial 22 with value: 0.8354918779124436.

Best trial: 22. Best value: 0.835492:  84%|████████▍ | 42/50 [53:46<10:10, 76.26s/it]

[I 2026-05-14 12:57:52,183] Trial 41 finished with value: 0.834081886821793 and parameters: {'xgb_n_estimators': 192, 'xgb_max_depth': 9, 'xgb_learning_rate': 0.011757695889229544, 'xgb_subsample': 0.9724777476742141, 'xgb_colsample_bytree': 0.7599724282453623, 'xgb_min_child_weight': 8, 'xgb_reg_alpha': 4.577739230961199e-07, 'xgb_reg_lambda': 0.598954075937556, 'lgbm_n_estimators': 457, 'lgbm_max_depth': 9, 'lgbm_learning_rate': 0.26160048562587246, 'lgbm_num_leaves': 109, 'lgbm_subsample': 0.7937003143962961, 'lgbm_colsample_bytree': 0.8879871890864893, 'lgbm_reg_alpha': 0.009762245050508812, 'lgbm_reg_lambda': 0.03315195969829253, 'cat_iterations': 295, 'cat_depth': 5, 'cat_learning_rate': 0.11557502573116767, 'cat_l2_leaf_reg': 0.034976689730194965, 'meta_C': 0.002811358980187654}. Best is trial 22 with value: 0.8354918779124436.

Best trial: 22. Best value: 0.835492:  86%|████████▌ | 43/50 [54:57<08:43, 74.78s/it]

[I 2026-05-14 12:59:03,498] Trial 42 finished with value: 0.8349970134672968 and parameters: {'xgb_n_estimators': 101, 'xgb_max_depth': 10, 'xgb_learning_rate': 0.012060674227558054, 'xgb_subsample': 0.9738738613030786, 'xgb_colsample_bytree': 0.8446579085069233, 'xgb_min_child_weight': 8, 'xgb_reg_alpha': 2.5543974363452475e-07, 'xgb_reg_lambda': 0.06447036113844588, 'lgbm_n_estimators': 460, 'lgbm_max_depth': 9, 'lgbm_learning_rate': 0.2071756104261844, 'lgbm_num_leaves': 102, 'lgbm_subsample': 0.80072334825617, 'lgbm_colsample_bytree': 0.8800334041946415, 'lgbm_reg_alpha': 0.0014160234907660222, 'lgbm_reg_lambda': 0.042927477170683494, 'cat_iterations': 255, 'cat_depth': 4, 'cat_learning_rate': 0.0944495758843032, 'cat_l2_leaf_reg': 0.02290768446043173, 'meta_C': 0.0005836865530545612}. Best is trial 22 with value: 0.8354918779124436.

Best trial: 43. Best value: 0.837754:  88%|████████▊ | 44/50 [56:10<07:25, 74.19s/it]

[I 2026-05-14 13:00:16,337] Trial 43 finished with value: 0.8377542917332355 and parameters: {'xgb_n_estimators': 101, 'xgb_max_depth': 10, 'xgb_learning_rate': 0.014950305774732326, 'xgb_subsample': 0.9544827433986524, 'xgb_colsample_bytree': 0.8448474207024385, 'xgb_min_child_weight': 7, 'xgb_reg_alpha': 1.5245664443779955e-07, 'xgb_reg_lambda': 0.0684486408443749, 'lgbm_n_estimators': 496, 'lgbm_max_depth': 10, 'lgbm_learning_rate': 0.11923124238613185, 'lgbm_num_leaves': 97, 'lgbm_subsample': 0.8133986409836893, 'lgbm_colsample_bytree': 0.9517151629893051, 'lgbm_reg_alpha': 1.6662828849589503e-06, 'lgbm_reg_lambda': 0.29815859338025424, 'cat_iterations': 182, 'cat_depth': 4, 'cat_learning_rate': 0.09972431755797273, 'cat_l2_leaf_reg': 0.018896827511493675, 'meta_C': 0.000621296157409663}. Best is trial 43 with value: 0.8377542917332355.

Best trial: 44. Best value: 0.838007:  90%|█████████ | 45/50 [57:25<06:11, 74.30s/it]

[I 2026-05-14 13:01:30,884] Trial 44 finished with value: 0.8380067095175316 and parameters: {'xgb_n_estimators': 104, 'xgb_max_depth': 10, 'xgb_learning_rate': 0.015018727307270193, 'xgb_subsample': 0.9757262389271871, 'xgb_colsample_bytree': 0.8547213679782314, 'xgb_min_child_weight': 8, 'xgb_reg_alpha': 1.308538322393431e-07, 'xgb_reg_lambda': 0.07144889325700708, 'lgbm_n_estimators': 521, 'lgbm_max_depth': 10, 'lgbm_learning_rate': 0.20978350446101024, 'lgbm_num_leaves': 95, 'lgbm_subsample': 0.8169197811860508, 'lgbm_colsample_bytree': 0.950946124342114, 'lgbm_reg_alpha': 1.951643051847528e-06, 'lgbm_reg_lambda': 0.2258518961119909, 'cat_iterations': 185, 'cat_depth': 4, 'cat_learning_rate': 0.08839444654337549, 'cat_l2_leaf_reg': 0.008602223178716336, 'meta_C': 0.00025092875854654625}. Best is trial 44 with value: 0.8380067095175316.

Best trial: 44. Best value: 0.838007:  92%|█████████▏| 46/50 [57:54<04:02, 60.75s/it]

[I 2026-05-14 13:02:00,011] Trial 45 finished with value: 0.8258030435478585 and parameters: {'xgb_n_estimators': 134, 'xgb_max_depth': 10, 'xgb_learning_rate': 0.025348712455524912, 'xgb_subsample': 0.8021691071053402, 'xgb_colsample_bytree': 0.8527599077592527, 'xgb_min_child_weight': 8, 'xgb_reg_alpha': 1.3525634584873446e-07, 'xgb_reg_lambda': 0.05441477827097674, 'lgbm_n_estimators': 528, 'lgbm_max_depth': 8, 'lgbm_learning_rate': 0.12429871377519518, 'lgbm_num_leaves': 18, 'lgbm_subsample': 0.8167441434210027, 'lgbm_colsample_bytree': 0.9542464732903695, 'lgbm_reg_alpha': 1.7123468370641209e-06, 'lgbm_reg_lambda': 0.2601871354132453, 'cat_iterations': 175, 'cat_depth': 3, 'cat_learning_rate': 0.0923683477032439, 'cat_l2_leaf_reg': 0.007632734118640019, 'meta_C': 0.0002923151502046025}. Best is trial 44 with value: 0.8380067095175316.

Best trial: 44. Best value: 0.838007:  94%|█████████▍| 47/50 [59:12<03:18, 66.05s/it]

[I 2026-05-14 13:03:18,418] Trial 46 finished with value: 0.8360778133319272 and parameters: {'xgb_n_estimators': 146, 'xgb_max_depth': 10, 'xgb_learning_rate': 0.016041043025711015, 'xgb_subsample': 0.927577145536474, 'xgb_colsample_bytree': 0.8154595621445115, 'xgb_min_child_weight': 8, 'xgb_reg_alpha': 6.867896665743001e-08, 'xgb_reg_lambda': 0.004058260025902842, 'lgbm_n_estimators': 587, 'lgbm_max_depth': 9, 'lgbm_learning_rate': 0.19577508427489496, 'lgbm_num_leaves': 82, 'lgbm_subsample': 0.7482059221590559, 'lgbm_colsample_bytree': 0.9220204080624032, 'lgbm_reg_alpha': 2.1740473892467603e-06, 'lgbm_reg_lambda': 0.7443311834836058, 'cat_iterations': 139, 'cat_depth': 4, 'cat_learning_rate': 0.07456752365089662, 'cat_l2_leaf_reg': 0.004467481342326047, 'meta_C': 0.0005843017146705047}. Best is trial 44 with value: 0.8380067095175316.

Best trial: 44. Best value: 0.838007:  96%|█████████▌| 48/50 [1:00:33<02:21, 70.58s/it]

[I 2026-05-14 13:04:39,583] Trial 47 finished with value: 0.8314488343702596 and parameters: {'xgb_n_estimators': 251, 'xgb_max_depth': 10, 'xgb_learning_rate': 0.0161021231078746, 'xgb_subsample': 0.9127091048361118, 'xgb_colsample_bytree': 0.8134146320379265, 'xgb_min_child_weight': 7, 'xgb_reg_alpha': 1.2186817597191351e-08, 'xgb_reg_lambda': 0.001468684913974319, 'lgbm_n_estimators': 575, 'lgbm_max_depth': 12, 'lgbm_learning_rate': 0.1354826023470676, 'lgbm_num_leaves': 77, 'lgbm_subsample': 0.7500249311915983, 'lgbm_colsample_bytree': 0.9784678102135531, 'lgbm_reg_alpha': 1.6393672751882377e-06, 'lgbm_reg_lambda': 6.6245420693767185, 'cat_iterations': 148, 'cat_depth': 4, 'cat_learning_rate': 0.06882478250782267, 'cat_l2_leaf_reg': 0.0027726129527086353, 'meta_C': 0.00024243716056967528}. Best is trial 44 with value: 0.8380067095175316.

Best trial: 44. Best value: 0.838007:  98%|█████████▊| 49/50 [1:01:54<01:13, 73.46s/it]

[I 2026-05-14 13:05:59,750] Trial 48 finished with value: 0.8333410533850032 and parameters: {'xgb_n_estimators': 146, 'xgb_max_depth': 10, 'xgb_learning_rate': 0.018772688030325536, 'xgb_subsample': 0.9304932594386797, 'xgb_colsample_bytree': 0.9201969056852639, 'xgb_min_child_weight': 8, 'xgb_reg_alpha': 6.602469182393772e-08, 'xgb_reg_lambda': 0.004871771569257112, 'lgbm_n_estimators': 593, 'lgbm_max_depth': 10, 'lgbm_learning_rate': 0.08383528711284347, 'lgbm_num_leaves': 83, 'lgbm_subsample': 0.8641523320372558, 'lgbm_colsample_bytree': 0.9232252942752782, 'lgbm_reg_alpha': 1.1464905351690616e-08, 'lgbm_reg_lambda': 0.6278634482712748, 'cat_iterations': 124, 'cat_depth': 3, 'cat_learning_rate': 0.03381183150575458, 'cat_l2_leaf_reg': 0.00418046574747948, 'meta_C': 0.00011489212378165262}. Best is trial 44 with value: 0.8380067095175316.

Best trial: 44. Best value: 0.838007: 100%|██████████| 50/50 [1:03:23<00:00, 76.07s/it]

[I 2026-05-14 13:07:29,243] Trial 49 finished with value: 0.8355387745815666 and parameters: {'xgb_n_estimators': 278, 'xgb_max_depth': 10, 'xgb_learning_rate': 0.015407484047874785, 'xgb_subsample': 0.619358102474579, 'xgb_colsample_bytree': 0.8750901080122574, 'xgb_min_child_weight': 1, 'xgb_reg_alpha': 3.3299884641953694e-08, 'xgb_reg_lambda': 0.000616203257238676, 'lgbm_n_estimators': 497, 'lgbm_max_depth': 11, 'lgbm_learning_rate': 0.15005785166320154, 'lgbm_num_leaves': 71, 'lgbm_subsample': 0.727186891702704, 'lgbm_colsample_bytree': 0.9546132918131258, 'lgbm_reg_alpha': 6.025807537109263e-08, 'lgbm_reg_lambda': 0.1215129012673256, 'cat_iterations': 132, 'cat_depth': 4, 'cat_learning_rate': 0.1489709417405859, 'cat_l2_leaf_reg': 0.010657549079951863, 'meta_C': 0.0012008671138771779}. Best is trial 44 with value: 0.8380067095175316.
Best F1-Macro: 0.8380067095175316
Best parameters:
{'xgb_n_estimators': 104, 'xgb_max_depth': 10, 'xgb_learning_rate': 0.015018727307270193, 'xgb_subsample': 0.9757262389271871, 'xgb_colsample_bytree': 0.8547213679782314, 'xgb_min_child_weight': 8, 'xgb_reg_alpha': 1.308538322393431e-07, 'xgb_reg_lambda': 0.07144889325700708, 'lgbm_n_estimators': 521, 'lgbm_max_depth': 10, 'lgbm_learning_rate': 0.20978350446101024, 'lgbm_num_leaves': 95, 'lgbm_subsample': 0.8169197811860508, 'lgbm_colsample_bytree': 0.950946124342114, 'lgbm_reg_alpha': 1.951643051847528e-06, 'lgbm_reg_lambda': 0.2258518961119909, 'cat_iterations': 185, 'cat_depth': 4, 'cat_learning_rate': 0.08839444654337549, 'cat_l2_leaf_reg': 0.008602223178716336, 'meta_C': 0.00025092875854654625}

In [12]:
# Compare base models using Optuna best parameters
best_params = study.best_params

base_models = {
    "xgb": XGBClassifier(
        n_estimators=best_params["xgb_n_estimators"],
        max_depth=best_params["xgb_max_depth"],
        learning_rate=best_params["xgb_learning_rate"],
        subsample=best_params["xgb_subsample"],
        colsample_bytree=best_params["xgb_colsample_bytree"],
        min_child_weight=best_params["xgb_min_child_weight"],
        reg_alpha=best_params["xgb_reg_alpha"],
        reg_lambda=best_params["xgb_reg_lambda"],
        objective="binary:logistic",
        eval_metric="logloss",
        random_state=RANDOM_STATE,
        n_jobs=-1
    ),
    "lgbm": LGBMClassifier(
        n_estimators=best_params["lgbm_n_estimators"],
        max_depth=best_params["lgbm_max_depth"],
        learning_rate=best_params["lgbm_learning_rate"],
        num_leaves=best_params["lgbm_num_leaves"],
        subsample=best_params["lgbm_subsample"],
        colsample_bytree=best_params["lgbm_colsample_bytree"],
        reg_alpha=best_params["lgbm_reg_alpha"],
        reg_lambda=best_params["lgbm_reg_lambda"],
        random_state=RANDOM_STATE,
        n_jobs=-1,
        verbose=-1
    ),
    "cat": CatBoostClassifier(
        iterations=best_params["cat_iterations"],
        depth=best_params["cat_depth"],
        learning_rate=best_params["cat_learning_rate"],
        l2_leaf_reg=best_params["cat_l2_leaf_reg"],
        random_seed=RANDOM_STATE,
        verbose=0,
        loss_function="Logloss"
    )
}

base_model_results = []
base_model_pipelines = {}

for name, model in base_models.items():
    pipe = Pipeline(
        steps=[
            ("preprocessor", preprocessing),
            ("model", model)
        ]
    )

    pipe.fit(X_train, y_train)
    base_model_pipelines[name] = pipe

    y_pred = pipe.predict(X_valid)
    y_proba = pipe.predict_proba(X_valid)[:, 1]

    best_threshold = 0.5
    best_macro_f1 = f1_score(y_valid, y_pred, average="macro")

    for threshold in np.linspace(0.05, 0.95, 181):
        threshold_pred = (y_proba >= threshold).astype(int)
        threshold_macro_f1 = f1_score(y_valid, threshold_pred, average="macro")

        if threshold_macro_f1 > best_macro_f1:
            best_threshold = threshold
            best_macro_f1 = threshold_macro_f1

    base_model_results.append({
        "model": name,
        "accuracy_default_0_5": accuracy_score(y_valid, y_pred),
        "macro_f1_default_0_5": f1_score(y_valid, y_pred, average="macro"),
        "roc_auc": roc_auc_score(y_valid, y_proba),
        "best_threshold": best_threshold,
        "macro_f1_best_threshold": best_macro_f1
    })

base_model_results = pd.DataFrame(base_model_results).sort_values(
    "macro_f1_best_threshold",
    ascending=False
)

base_model_results

,model,accuracy_default_0_5,macro_f1_default_0_5,roc_auc,best_threshold,macro_f1_best_threshold
1,lgbm,0.911693,0.849967,0.913943,0.560,0.852575
0,xgb,0.904346,0.821250,0.909216,0.685,0.837525
2,cat,0.904806,0.828650,0.911605,0.670,0.834683

In [13]:
best_params = study.best_params

final_xgb = XGBClassifier(
    n_estimators=best_params["xgb_n_estimators"],
    max_depth=best_params["xgb_max_depth"],
    learning_rate=best_params["xgb_learning_rate"],
    subsample=best_params["xgb_subsample"],
    colsample_bytree=best_params["xgb_colsample_bytree"],
    min_child_weight=best_params["xgb_min_child_weight"],
    reg_alpha=best_params["xgb_reg_alpha"],
    reg_lambda=best_params["xgb_reg_lambda"],
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=RANDOM_STATE,
    n_jobs=-1
)

final_lgbm = LGBMClassifier(
    n_estimators=best_params["lgbm_n_estimators"],
    max_depth=best_params["lgbm_max_depth"],
    learning_rate=best_params["lgbm_learning_rate"],
    num_leaves=best_params["lgbm_num_leaves"],
    subsample=best_params["lgbm_subsample"],
    colsample_bytree=best_params["lgbm_colsample_bytree"],
    reg_alpha=best_params["lgbm_reg_alpha"],
    reg_lambda=best_params["lgbm_reg_lambda"],
    random_state=RANDOM_STATE,
    n_jobs=-1,
    verbose=-1
)

final_cat = CatBoostClassifier(
    iterations=best_params["cat_iterations"],
    depth=best_params["cat_depth"],
    learning_rate=best_params["cat_learning_rate"],
    l2_leaf_reg=best_params["cat_l2_leaf_reg"],
    random_seed=RANDOM_STATE,
    verbose=0,
    loss_function="Logloss"
)

final_meta = LogisticRegression(
    C=best_params["meta_C"],
    max_iter=3000,
    class_weight="balanced",
    random_state=RANDOM_STATE
)

final_stack_model = StackingClassifier(
    estimators=[
        ("xgb", final_xgb),
        ("lgbm", final_lgbm),
        ("cat", final_cat)
    ],
    final_estimator=final_meta,
    cv=skf,
    stack_method="predict_proba",
    n_jobs=-1,
    passthrough=False
)

final_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessing),
        ("model", final_stack_model)
    ]
)

final_pipeline.fit(X, y)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('numeric',
                                                  SimpleImputer(strategy='median'),
                                                  ['income_yearly',
                                                   'debt_ratio',
                                                   'credit_rating',
                                                   'amount_requested',
                                                   'interest_pct']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(fill_value='Missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))...
                                                                subsample=0.8169197811860508,
                                                                verbose=-1)),
                                                ('cat',
                                                 CatBoostClassifier(depth=4, iterations=185, l2_leaf_reg=0.008602223178716336, learning_rate=0.08839444654337549, loss_function='Logloss', random_seed=42, verbose=0))],
                                    final_estimator=LogisticRegression(C=0.00025092875854654625,
                                                                       class_weight='balanced',
                                                                       max_iter=3000,
                                                                       random_state=42),
                                    n_jobs=-1, stack_method='predict_proba'))])

In [29]:
test_pred = final_pipeline.predict(df_test)
test_proba = final_pipeline.predict_proba(df_test)[:, 1]

test_predictions = pd.DataFrame({
    "id": df_test["cust_id"],
    "is_repaid": test_pred.astype(int)
})

test_predictions.to_csv("submission_loan_final.csv", index=False)
test_predictions.head()

   id  is_repaid
0   1          1
1   2          1
2   3          1
3   4          1
4   5          1